[tool.poetry]
name = "cbrapi"
version = "0.1.7"
description = "Python interface for Central Bank of Russia (CBR) API"
authors = [
    "AAARRRT <artiomsalazov@gmail.com>",
    "MBK Development LLC <info@rostsber.ru>"
]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = ">=3.10,<4.0.0"
pandas = ">=2.3.2,<4.0.0"
requests = "*"
suds-py3 = "*"
lxml = "*"
ipykernel = "*"

[tool.poetry.group.dev.dependencies]
ruff = "*"
pytest = "*"
pytest-mock = "*"
scipy-stubs = "*"  # for typehints

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 120
extend-exclude = ["docs", ".ipynb_checkpoints", "env", ".env"]
target-version = "py310"

[tool.ruff.lint]
select = ["C", "E", "F", "W", "B", "UP"]
ignore = ["E203", "E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]


